// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyPLaB_YWfdAvBqUFe-z3gPHUbhk9xhq0',
    appId: '1:35722781000:android:ef3e275969cb074c8d937d',
    messagingSenderId: '35722781000',
    projectId: 'muvo-40597',
    storageBucket: 'muvo-40597.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjm6YPFWrynJrQKzX70xnVl-_X8lmr6sY',
    appId: '1:35722781000:ios:f219b8ccbfa4438d8d937d',
    messagingSenderId: '35722781000',
    projectId: 'muvo-40597',
    storageBucket: 'muvo-40597.firebasestorage.app',
    androidClientId: '35722781000-cmvfnblf11flq7tocoqas0l639s80ekp.apps.googleusercontent.com',
    iosClientId: '35722781000-uapv7r6ofcrr3l0u11tccgtf23bprqim.apps.googleusercontent.com',
    iosBundleId: 'com.andrew.muvo',
  );
}
